# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 1bd3c3184f84f32174241ec2c0b05d617b421a00067c776ab40bc6541e1fd4bc792e061cea54411cfb8195d07eb1fbbd8b4aaa2626219578efe0133cdda5e058

test:
  secret_key_base: 05b684cd2edb2bd10dec57044c5cce00a94bb334c8eab9cd1a845a8e02eec8432e8c8c41c2c36f2faa926411e67b6053c85c1a5e4c643baa4bc926e62f380c71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
